micronaut:
  function:
    name: generate-client-token
  server:
    port: 8083
    cors:
      enabled: true
      configurations:
        web:
          allowedOrigins:
            - http://localhost:4200
          allowedMethods:
            - POST